[package]
name = "mongo_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2"
serde = "1"
serde_json = "1"
tokio = { version = "1.21.1", features = ["full"] }
futures = "0.3.24"